import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutWireframe from "@/commons/layout";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { AuthProvider } from "@/commons/providers/auth/auth.provider";
import { AuthGuard } from "@/commons/providers/auth/auth.guard";
import ApolloClientProvider from "@/commons/providers/apollo-client/apollo-client.provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ApolloClientProvider>
            <ModalProvider>
              <AuthGuard>
                <LayoutWireframe>{children}</LayoutWireframe>
              </AuthGuard>
            </ModalProvider>
          </ApolloClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
